# Generated by Django 5.1.1 on 2024-09-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_gtd', models.CharField(max_length=256)),
                ('reference_gtd', models.CharField(max_length=256)),
                ('date_recorded', models.CharField(max_length=256)),
                ('customs_mode', models.CharField(choices=[('IM70', 'IM 70'), ('IM40', 'IM 40'), ('ND40', 'ND 40')], max_length=10)),
                ('country', models.CharField(max_length=256)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('F', 'Finished'), ('I', 'In process')], max_length=1)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ManyToManyField(related_name='recievers', to='app.company')),
                ('sender', models.ManyToManyField(related_name='senders', to='app.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
